### ISSUE TITLE
Hyper 3 release notes include Electron v4, blog post states v3

### ISSUE THREAD

**Issue by noderat** [zeit/hyper-site#126]
![image](https://user-images.githubusercontent.com/89279/57268008-6b7b3d00-703f-11e9-80f6-69962c81df9e.png)

doesn't quite match the blog post:

![image](https://user-images.githubusercontent.com/89279/57268028-7afa8600-703f-11e9-9993-de0acc167092.png)

**Comment by timothyis** [comment]
Thanks for the issue @noderat. What the blog post lists is correct, so I'll close this issue. 
I'll also edit the release note to fix the type 🙏
