### ISSUE TITLE
Incorrect platform detection — Allow manual selection

### ISSUE THREAD

**Issue by jsejcksn** [zeit/hyper-site#157]
Platform detection is not working correctly on the website:

<img width="1281" alt="detected-linux-actually-mac" src="https://user-images.githubusercontent.com/868251/67222602-43b44180-f3f3-11e9-8cf9-258829040237.png">

This causes incorrect info to be displayed regarding paths:

<img width="1281" alt="linux-paths" src="https://user-images.githubusercontent.com/868251/67222719-7d854800-f3f3-11e9-8399-5af96169ee98.png">

If manual selection of platform were possible, this could be corrected, but I don't see that there is a way to manually select my platform. Perhaps this can be added.

Environment in screenshots:
**OS**: macOS 10.15
**Browser**: Chrome 77.0.3865.120 (Incognito—No extensions)

**Comment by jsejcksn** [comment]
When visiting the site today, it appears that path references have been removed entirely. I think this is less helpful than allowing new users to select the correct platform and see the correct paths for the platform.

**Comment by dotnetCarpenter** [comment]
`User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0`

![hyper](https://user-images.githubusercontent.com/43763/68320743-cf4ef300-00c0-11ea-9626-fda055515547.png)

OS: Linux Mint 19.2 Tina

Code that need fix: https://github.com/zeit/hyper-site/blob/master/pages/index.js#L42-L62

**Comment by pacocoursey** [comment]
Thanks guys, closing as the User Agent detection has been fixed in #165.

Manual selection is a good idea, if you still feel strongly about adding it as a feature please open a new issue.
