### ISSUE TITLE
Low audit scores

### ISSUE THREAD

**Issue by vassbence** [zeit/hyper-site#171]
Hey!

The site could use a little bit of elbow grease, the audit scores are quite low for a fully static website. I'll try my best clean up the repo, use the latest Next.js features, etc. I'll note any changes that are not part of the 1:1 rewrite but made sense for one reason or antoher.

See current progress in #172.

Let me know if you want anything else fixed, also I would love to receive some feedback.

**Comment by pacocoursey** [comment]
Looking good! Another big area of improvement is removing `getInitialProps` from all pages in favor of fully static pages.

**Comment by vassbence** [comment]
Notable change: removed `getInitialProps` from the [source-code viewer page](https://github.com/zeit/hyper-site/pull/172/commits/6d9af58eb37a2792029d152b6b7811f473640213#diff-3dd104481624b23c933a4f5add1dc430) and opted for showing nothing until the contents are fetched, then play a 200ms appear animation.

**Comment by vassbence** [comment]
Notable change: [renamed](https://github.com/zeit/hyper-site/pull/172/commits/0a85dc5792639bb61484fa4dc343bda0da3da19a) the `/plugin/[id]` path to `/store/[id]` as the meta tags and document title already read `Hyper Store` + it makes more sense since we have both plugins and themes under this url.

**Comment by vassbence** [comment]
Notable change: Removed MDX and the wrapper component -- it was hard coded with the single blog post's meta. Will replace with a better rehype/remark based SSG solution later.

**Comment by vassbence** [comment]
Let me know if you want me to update the font-stack to use Inter due to the [Chrome bug ](https://www.coywolf.news/webmaster/chrome-81-breaks-system-fonts-bold/) or just wait it out (and see what vercel.com uses after bugfix).
