### ISSUE TITLE
Switch to `micro` from `express` for the server implementation

### ISSUE THREAD

**Issue by styfle** [zeit/hyper-site#20]
I thought [micro](https://github.com/zeit/micro) was the zeit choice for http servers.
Why is this project using express?

**Comment by MAPESO** [comment]
My fault, for the personalized routes I decided to use express, it did not occur to me to use ``micro`` 😿

**Comment by styfle** [comment]
Okay thanks for the clarification 👍 

I look forward to see how you migrate because that might be a good example for others who want to switch from `express` to `micro` 😄

**Comment by MAPESO** [comment]
@styfle @timothyis I'll take care of making the migraciona to micro ❤️ 

Thank you for making this excellent question 🙏

**Comment by timneutkens** [comment]
Fixed 👍
