### ISSUE TITLE
Guidelines for plugin image submissions

### ISSUE THREAD

**Issue by MAPESO** [zeit/hyper-site#31]
This is a topic a little more related to the design, Currently all the themes that are in hyper store are following this line of design. It should be mandatory to follow this design line only in themes.

@evilrabbit 🐰 I would like to know your opinion about this

![hyper-chesterish](https://user-images.githubusercontent.com/16585386/38890452-1193a880-4247-11e8-912c-b9b46c0d98f5.png)

**Comment by timothyis** [comment]
I'm working on updating the wiki to add guidelines for the images we will accept.

**Comment by MAPESO** [comment]
@timothyis wonderful 😍

**Comment by ahmadawais** [comment]
Is there a way to showcase how that's been done? Also, I think it's too simple, what if we can use git on the left-hand side to showcase how a theme greets Git changes/clean branch.

**Comment by timothyis** [comment]
@ahmadawais I don't think we should overcrowd the images, but I definitely think that could be a good idea. Would you be able to add a screenshot to this thread to show how you're picturing it?

**Comment by bzaman** [comment]
@ahmadawais Hi, its a great theme I think. A details about your git integration with powerline fonts would be a great approach for us to implement it. Thanks

**Comment by ahmadawais** [comment]
@bzaman Thanks for that. That's coming from ZSH + my Shades of Purple Zsh theme that you can find here https://github.com/ahmadawais/shades-of-purple-iterm2.

I guess I'll add that to the readme.

**Comment by bzaman** [comment]
@ahmadawais Thank you for your very quick replay.

**Comment by simonhaenisch** [comment]
@ahmadawais I just searched for something like "terminal print colors" on Google and found a script that does it... wrapped it in a zsh function for myself:

```zsh
function printcolors() {
  echo
  echo -e "\033[0mNC (No color)"
  echo -e "\033[1;37mWHITE   \033[0;30mBLACK"
  echo -e "\033[0;34mBLUE    \033[1;34mLIGHT_BLUE"
  echo -e "\033[0;32mGREEN   \033[1;32mLIGHT_GREEN"
  echo -e "\033[0;36mCYAN    \033[1;36mLIGHT_CYAN"
  echo -e "\033[0;31mRED     \033[1;31mLIGHT_RED"
  echo -e "\033[0;35mPURPLE  \033[1;35mLIGHT_PURPLE"
  echo -e "\033[0;33mYELLOW  \033[1;33mLIGHT_YELLOW"
  echo -e "\033[1;30mGRAY    \033[0;37mLIGHT_GRAY"
}
```

**Comment by pacocoursey** [comment]
Details for image submissions are now included in the wiki:

https://github.com/zeit/hyper-site/wiki/Submitting-a-new-plugin-or-theme-to-Hyper-Store#3-submit-your-plugin-or-theme-to-hyper-store

> A preview image of your plugin or theme. Can be a gif, png, jpeg, etc. Recommended dimensions are 600x400 pixels but it'd be perfect if you could make the density 2x for retina screens (1200x800)
