### ISSUE TITLE
Theme Awesomeness Check

### ISSUE THREAD

**Issue by novddd** [zeit/hyper-site#60]
Love the store and how it looks! Thank you all a lot for your work!
I am using this theme lately and I was thinking if it would be a good fit for the store;
- Link: https://github.com/klauscfhq/hyperocean
- Screenshot::
![ocean](https://user-images.githubusercontent.com/24556287/42119360-69e07c92-7c13-11e8-9e7a-505819c01c9c.png)
If you think it is interesting enough I can create a pull request! Thank you again for your time!

**Comment by timothyis** [comment]
Looks amazing and would love a PR for it!

**Comment by novddd** [comment]
Awesome! Is that is OK to be used or is a new one needed? Thank you a lot for your quick answer!

**Comment by kingmoduk** [comment]
Send me link.





###
