### ISSUE TITLE
Display version number on website

### ISSUE THREAD

**Issue by MartinMuzatko** [zeit/hyper-site#64]
From https://github.com/zeit/hyper/issues/3153:

It would be nice to see the latest official version of hyper on the website near the download buttons.

Maybe it would be nice to also note what release channel is on which version.

As already mentioned in the other issue, the version number (latest/prerelease) can be obtained via the github api or if there is a build setup - during buildtime you can pass env vars maybe

```js
response = await fetch('https://api.github.com/repos/zeit/hyper/releases')
releases = await response.json()
latestStable = releases.find(release => !release.prerelease)
console.log(latestStable.tag_name)
```

**Comment by oguzzkilic** [comment]
Hi @MartinMuzatko 

Is this what you were talking about?

![latest-version](https://user-images.githubusercontent.com/3652404/52178889-9eb1f400-27e4-11e9-8037-ae2a579a80e6.png)

**Comment by MartinMuzatko** [comment]
Yes :) that would be nice

**Comment by oguzzkilic** [comment]
I submitted a pull request for the issue :)

**Comment by cjoshmartin** [comment]
@timneutkens @MartinMuzatko @oguzzkilic  Shouldn't this issue be closed?

**Comment by MartinMuzatko** [comment]
The PR is closed but the website is not refreshed. Is this possible?

![image](https://user-images.githubusercontent.com/2950505/53431054-104e1e00-39f0-11e9-8cd6-360e5934bc97.png)

**Comment by timneutkens** [comment]
I've asked @timothyis to deploy the site 🙏

**Comment by timothyis** [comment]
Sorry for the delay, I just got to deploying, it should now be live!

**Comment by timothyis** [comment]
Apologies again, but I'm re-opening this. It seems to be 500ing after a few minutes of being aliased for some reason 😓

**Comment by timothyis** [comment]
I have submitted a fix for the 500 error, which spawned from the GitHub rate limit https://github.com/zeit/hyper-site/pull/105

**Comment by MartinMuzatko** [comment]
So little changes can do so much harm 😨 
Hope everything is okay now!

**Comment by pacocoursey** [comment]
We should be back to consistently showing the latest stable version on the website now. Thanks!
