### ISSUE TITLE
Limited activity on API providing package metadata

### ISSUE THREAD

**Issue by greg-harrison** [zeit/hyper-site#74]
It appears as though the service from which the site was getting package metadata (npms.io) is no longer being maintained.

I suggest making the calls against registry.npmjs.org, though this will require reworking some of the fields that were expected to be coming out of the "metadata" object.

Calls to registry.npmjs.org can be made as follows `https://registry.npmjs.org/${name}/latest` to retrieve the latest data on a package.

**Comment by timothyis** [comment]
Hi @greg-harrison, sorry for the late response here. There are a few features that npms.io give that the npm registry did not (at least before). Would you be able to perhaps submit a PR with the suggested changes?

**Comment by pacocoursey** [comment]
Closing, thanks @oguzzkilic!
