### ISSUE TITLE
Link to spectrum chat in readme doesn't work

### ISSUE THREAD

**Issue by amilajack** [zeit/hyper-site#75]
<img width="1280" alt="screen shot 2018-09-25 at 7 07 46 pm" src="https://user-images.githubusercontent.com/6374832/46053092-5841df80-c0f6-11e8-93cf-3ccdee286eb3.png">

**Comment by MAPESO** [comment]
Thanks for report ❤️ 
Sorry for the delay in answering, we are a bit busy with other activities 🙍 😿

**Comment by MAPESO** [comment]
@amilajack problem solved #77 😸
